In [1]:
# All other dependencies are imported in project_example
from project_example import *
import matplotlib.pyplot as plt

In [2]:
# data .... is a Pandas dataframe
data = load_data("active1000")

In [3]:
# data .... number of dimensions
data.ndim

2

In [4]:
# data .... indexes
data.index

RangeIndex(start=0, stop=2207608, step=1)

In [5]:
# data .... column titles
data.columns

Index(['eventId', 'category', 'activeTime', 'title', 'url', 'userId',
       'publishtime', 'time', 'documentId'],
      dtype='object')

In [6]:
# data .... data-types
data.dtypes

eventId          int64
category        object
activeTime     float64
title           object
url             object
userId          object
publishtime     object
time             int64
documentId      object
dtype: object

In [7]:
data.head()

eventId           category  activeTime  \
0  2059407368               None         9.0   
1   682091708               None         NaN   
2  2064579395    nyheter|okonomi         NaN   
3   709984968               None        32.0   
4   114179448  nyheter|trondheim        48.0   

                                              title  \
0                                              None   
1                                              None   
2  - Landet bygges ikke bare mellom klokken 8 og 16   
3                                              None   
4                   To innbruddsforsøk på tre dager   

                                                 url  \
0                                  http://adressa.no   
1                                  http://adressa.no   
2  http://adressa.no/nyheter/okonomi/2017/02/25/l...   
3                                  http://adressa.no   
4  http://adressa.no/nyheter/trondheim/2017/02/25...   

                                        userId               publishtime  \
0  cx:2ry8kk0pg92r51msqcyu96z5u6:3mhvo7hdj9g6y                      None   
1   cx:16lfhhoa0byyq3c06phiivxcas:qf0oz0oiyr1g                      None   
2     cx:13512028457711940833770:1cg93fqzhke70  2017-02-25T16:47:38.000Z   
3            cx:htkipe5w759w5vw9:2souxtezokfus                      None   
4  cx:2ry8kk0pg92r51msqcyu96z5u6:3mhvo7hdj9g6y  2017-02-25T20:29:21.000Z   

         time                                documentId  
0  1488063609                                      None  
1  1488063624                                      None  
2  1488063624  cbfe5a35b79b2362796607c1e381a5f835394aa4  
3  1488063625                                      None  
4  1488063629  b3aa4b3a8d5f22ea512f67fd2b9ce0a572de0323

In [8]:
# ratings .... is of type numpy.ndarray
ratings = load_dataset(data)

/home/vanja/MINE/AI/Recommender/Recommender/project_example.py:69: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=['userId', 'documentId'], inplace=True)


In [9]:
# ratings .... matrix shape 
print(ratings.shape)

(1000, 20344)


In [10]:
# ratings .... confirming type is numpy.ndarray
print(type(ratings))

<class 'numpy.ndarray'>


In [11]:
# Running the statistics on complete data set
statistics(data)

Total number of events(front page incl.): 2207608
Total number of events(without front page): 788931
Total number of documents: 20344
Sparsity: 3.878%


/home/vanja/MINE/AI/Recommender/Recommender/project_example.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ref.drop_duplicates(subset=['userId', 'documentId'], inplace=True)


Total number of events(drop duplicates): 679355
Sparsity (drop duplicates): 3.339%
Describe by user:
            counts
count  1000.000000
mean    679.355000
std     333.619737
min      59.000000
25%     506.750000
50%     639.500000
75%     797.500000
max    7958.000000


In [12]:
# Evaluating only a slice of data
# Running the complete set resultet in kernel breakdown
sinRec, df = content_processing(data[:100])

Dimension of feature vector: (30, 20)
Similarity Matrix:
[[1.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         1.         0.18170716]
 [0.         0.         0.18170716 1.        ]]


/home/vanja/MINE/AI/Recommender/Recommender/project_example.py:186: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=['userId', 'documentId'], inplace=True)
/home/vanja/MINE/AI/Recommender/Recommender/project_example.py:187: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category'] = df['category'].str.split('|')
/home/vanja/MINE/AI/Recommender/Recommender/project_example.py:188: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the cav

In [13]:
newSet = load_dataset_activeTime(data)

In [14]:
newSet.head(20)

activeTime  \
documentId                                  0006b2caef9ae801cfa0a48ec737544241ec4dca   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   
cx:1308583952725345187693:udud1r6r2t9x                                           NaN   
cx:1309558690741378897676:2952b0y4ym2yb                                          NaN   
cx:13107309109141761847803:1e1rswsawyyc3                                         NaN   
cx:13107395951811145781879:31h108vvvw6te                                         NaN   
cx:1311701842831565911801:20af369r0nju6                                          NaN   
cx:131949358793188181088:2r9pmm9tjpi2l                                           NaN   
cx:1320775268464546183553:s7oe3e2pg0in                                           NaN   
cx:13230374570232135078687:3ng976ttdk2la                                         NaN   
cx:1323088975693404397604:wi004nwg1lgv                                           NaN   
cx:13231052697351750699011:3ojtggg4sfae8                                         NaN   
cx:13233863419858515505:13cyrrnk4fgs                                             NaN   
cx:1323497097529909214432:2v6w9llo94ysn                                          NaN   
cx:1323509040300815435511:ig1xw0bd55kp                                           NaN   
cx:1324824046614510500110:3246ixkuby1u3                                          NaN   
cx:13248361004781723078120:2wmidk0ara9mw                                         NaN   

                                                                                      \
documentId                                  00098cc438af89c1ba8fb6a37035af2e2f606ce3   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   
cx:1308583952725345187693:udud1r6r2t9x                                           NaN   
cx:1309558690741378897676:2952b0y4ym2yb                                          NaN   
cx:13107309109141761847803:1e1rswsawyyc3                                         NaN   
cx:13107395951811145781879:31h108vvvw6te                                         NaN   
cx:1311701842831565911801:20af369r0nju6                                          NaN   
cx:131949358793188181088:2r9pmm9tjpi2l                                           NaN   
cx:1320775268464546183553:s7oe3e2pg0in                                           NaN   
cx:13230374570232135078687:3ng976ttdk2la                                         NaN   
cx:1323088975693404397604:wi004nwg1lgv                                           NaN   
cx:13231052697351750699011:3ojtggg4sfae8                                         NaN   
cx:13233863419858515505:13cyrrnk4fgs                                             NaN   
cx:1323497097529909214432:2v6w9llo94ysn                                          NaN   
cx:1323509040300815435511:ig1xw0bd55kp                                           NaN   
cx:1324824046614510500110:3246ixkuby1u3                                          NaN   
cx:13248361004781723078120:2wmidk0ara9mw                                         NaN   

                        

In [15]:
#newSet['activeTime'] = newSet['activeTime'].fillna(0)

In [16]:
newSet.head(20)

activeTime  \
documentId                                  0006b2caef9ae801cfa0a48ec737544241ec4dca   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   
cx:1308583952725345187693:udud1r6r2t9x                                           NaN   
cx:1309558690741378897676:2952b0y4ym2yb                                          NaN   
cx:13107309109141761847803:1e1rswsawyyc3                                         NaN   
cx:13107395951811145781879:31h108vvvw6te                                         NaN   
cx:1311701842831565911801:20af369r0nju6                                          NaN   
cx:131949358793188181088:2r9pmm9tjpi2l                                           NaN   
cx:1320775268464546183553:s7oe3e2pg0in                                           NaN   
cx:13230374570232135078687:3ng976ttdk2la                                         NaN   
cx:1323088975693404397604:wi004nwg1lgv                                           NaN   
cx:13231052697351750699011:3ojtggg4sfae8                                         NaN   
cx:13233863419858515505:13cyrrnk4fgs                                             NaN   
cx:1323497097529909214432:2v6w9llo94ysn                                          NaN   
cx:1323509040300815435511:ig1xw0bd55kp                                           NaN   
cx:1324824046614510500110:3246ixkuby1u3                                          NaN   
cx:13248361004781723078120:2wmidk0ara9mw                                         NaN   

                                                                                      \
documentId                                  00098cc438af89c1ba8fb6a37035af2e2f606ce3   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   
cx:1308583952725345187693:udud1r6r2t9x                                           NaN   
cx:1309558690741378897676:2952b0y4ym2yb                                          NaN   
cx:13107309109141761847803:1e1rswsawyyc3                                         NaN   
cx:13107395951811145781879:31h108vvvw6te                                         NaN   
cx:1311701842831565911801:20af369r0nju6                                          NaN   
cx:131949358793188181088:2r9pmm9tjpi2l                                           NaN   
cx:1320775268464546183553:s7oe3e2pg0in                                           NaN   
cx:13230374570232135078687:3ng976ttdk2la                                         NaN   
cx:1323088975693404397604:wi004nwg1lgv                                           NaN   
cx:13231052697351750699011:3ojtggg4sfae8                                         NaN   
cx:13233863419858515505:13cyrrnk4fgs                                             NaN   
cx:1323497097529909214432:2v6w9llo94ysn                                          NaN   
cx:1323509040300815435511:ig1xw0bd55kp                                           NaN   
cx:1324824046614510500110:3246ixkuby1u3                                          NaN   
cx:13248361004781723078120:2wmidk0ara9mw                                         NaN   

                        

In [17]:
newSet.min()

            documentId                              
activeTime  0006b2caef9ae801cfa0a48ec737544241ec4dca    35.0
            00098cc438af89c1ba8fb6a37035af2e2f606ce3    21.0
            000fd9e1ee3153e955d5e64b35691d799189aa2d     1.0
            0020dd5ded93f94d4d078151a7733bb8410838fd     2.0
            0022652ffa4a9f8a041b5b4fb7591aacda920d31    29.0
                                                        ... 
            ffe7344b2550c475de286de0f34da337b1af1851     1.0
            ffea2777d7703dc7307e9a6333657cfb4bf6131e    26.0
            ffeea037b0cf89ab7b2ad06d1494537fb7b9954d    58.0
            fff0ee44bb6de4dcab4828abfa90302af0f30d36     1.0
            fffcc5d96f6d91418c68b17c191eb25093947b37    79.0
Length: 14351, dtype: float64

In [18]:
newSet.max()

            documentId                              
activeTime  0006b2caef9ae801cfa0a48ec737544241ec4dca    148.0
            00098cc438af89c1ba8fb6a37035af2e2f606ce3     86.0
            000fd9e1ee3153e955d5e64b35691d799189aa2d    143.0
            0020dd5ded93f94d4d078151a7733bb8410838fd    226.0
            0022652ffa4a9f8a041b5b4fb7591aacda920d31     29.0
                                                        ...  
            ffe7344b2550c475de286de0f34da337b1af1851    458.0
            ffea2777d7703dc7307e9a6333657cfb4bf6131e    146.0
            ffeea037b0cf89ab7b2ad06d1494537fb7b9954d    185.0
            fff0ee44bb6de4dcab4828abfa90302af0f30d36    367.0
            fffcc5d96f6d91418c68b17c191eb25093947b37     79.0
Length: 14351, dtype: float64

In [19]:
newSet.mean()

            documentId                              
activeTime  0006b2caef9ae801cfa0a48ec737544241ec4dca     89.666667
            00098cc438af89c1ba8fb6a37035af2e2f606ce3     57.500000
            000fd9e1ee3153e955d5e64b35691d799189aa2d     36.444444
            0020dd5ded93f94d4d078151a7733bb8410838fd     61.448276
            0022652ffa4a9f8a041b5b4fb7591aacda920d31     29.000000
                                                           ...    
            ffe7344b2550c475de286de0f34da337b1af1851     49.391304
            ffea2777d7703dc7307e9a6333657cfb4bf6131e     83.333333
            ffeea037b0cf89ab7b2ad06d1494537fb7b9954d    121.500000
            fff0ee44bb6de4dcab4828abfa90302af0f30d36     89.541284
            fffcc5d96f6d91418c68b17c191eb25093947b37     79.000000
Length: 14351, dtype: float64

In [20]:
clean = load_dataset_activeTime(data)

In [21]:
clean.head()

activeTime  \
documentId                                  0006b2caef9ae801cfa0a48ec737544241ec4dca   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  00098cc438af89c1ba8fb6a37035af2e2f606ce3   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  000fd9e1ee3153e955d5e64b35691d799189aa2d   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                        15.0   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0020dd5ded93f94d4d078151a7733bb8410838fd   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0022652ffa4a9f8a041b5b4fb7591aacda920d31   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0023cf8c8637599ee493463a429f4af62817cf3a   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:130821260123614207

In [22]:
clean.isnull().sum().sum()

13904481

In [23]:
clean = clean * (1.0/clean.mean())

In [24]:
clean.isnull().sum().sum()

13904481

In [25]:
clean.mean()

            documentId                              
activeTime  0006b2caef9ae801cfa0a48ec737544241ec4dca    1.0
            00098cc438af89c1ba8fb6a37035af2e2f606ce3    1.0
            000fd9e1ee3153e955d5e64b35691d799189aa2d    1.0
            0020dd5ded93f94d4d078151a7733bb8410838fd    1.0
            0022652ffa4a9f8a041b5b4fb7591aacda920d31    1.0
                                                       ... 
            ffe7344b2550c475de286de0f34da337b1af1851    1.0
            ffea2777d7703dc7307e9a6333657cfb4bf6131e    1.0
            ffeea037b0cf89ab7b2ad06d1494537fb7b9954d    1.0
            fff0ee44bb6de4dcab4828abfa90302af0f30d36    1.0
            fffcc5d96f6d91418c68b17c191eb25093947b37    1.0
Length: 14351, dtype: float64

In [26]:
clean.min().min()

0.0012699585531708558

In [27]:
clean.max().max()

73.00737730468616

In [28]:
clean.median().median()

1.0

In [29]:
clean.head()

activeTime  \
documentId                                  0006b2caef9ae801cfa0a48ec737544241ec4dca   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  00098cc438af89c1ba8fb6a37035af2e2f606ce3   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  000fd9e1ee3153e955d5e64b35691d799189aa2d   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                    0.411585   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0020dd5ded93f94d4d078151a7733bb8410838fd   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0022652ffa4a9f8a041b5b4fb7591aacda920d31   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0023cf8c8637599ee493463a429f4af62817cf3a   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:130821260123614207

In [30]:
print(clean.activeTime.min())

documentId
0006b2caef9ae801cfa0a48ec737544241ec4dca    0.390335
00098cc438af89c1ba8fb6a37035af2e2f606ce3    0.365217
000fd9e1ee3153e955d5e64b35691d799189aa2d    0.027439
0020dd5ded93f94d4d078151a7733bb8410838fd    0.032548
0022652ffa4a9f8a041b5b4fb7591aacda920d31    1.000000
                                              ...   
ffe7344b2550c475de286de0f34da337b1af1851    0.020246
ffea2777d7703dc7307e9a6333657cfb4bf6131e    0.312000
ffeea037b0cf89ab7b2ad06d1494537fb7b9954d    0.477366
fff0ee44bb6de4dcab4828abfa90302af0f30d36    0.011168
fffcc5d96f6d91418c68b17c191eb25093947b37    1.000000
Length: 14351, dtype: float64


In [31]:
clean.columns

MultiIndex([('activeTime', '0006b2caef9ae801cfa0a48ec737544241ec4dca'),
            ('activeTime', '00098cc438af89c1ba8fb6a37035af2e2f606ce3'),
            ('activeTime', '000fd9e1ee3153e955d5e64b35691d799189aa2d'),
            ('activeTime', '0020dd5ded93f94d4d078151a7733bb8410838fd'),
            ('activeTime', '0022652ffa4a9f8a041b5b4fb7591aacda920d31'),
            ('activeTime', '0023cf8c8637599ee493463a429f4af62817cf3a'),
            ('activeTime', '002472431520087fcb7bc36fc544495885e8ab39'),
            ('activeTime', '002536e7cb357867c9d935353b3a3b046a6766fa'),
            ('activeTime', '0027cd61894c015bf8cc0450e7b938d4525ea74f'),
            ('activeTime', '002c0d3d88f21091546fdbbaf53d25b2c0f3a259'),
            ...
            ('activeTime', 'ffd4cfd10d5acc9f14c022b94f714376a36bf716'),
            ('activeTime', 'ffdc3ea5ba4d307e6412e69c16bf1fdd6b90c5a5'),
            ('activeTime', 'ffe116360c76b3f0ead618448b019cf35d22134a'),
            ('activeTime', 'ffe19ee6d15dc317d141

In [32]:
print(clean.activeTime.index.get_level_values(level=0))

Index(['cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7',
       'cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694',
       'cx:13077170178592105431908:2so1nc52xur4d',
       'cx:13082126012361420762846:3nhzg71lk2zqc',
       'cx:13082926635761580649288:30q2cgmwa3mzi',
       'cx:1308583952725345187693:udud1r6r2t9x',
       'cx:1309558690741378897676:2952b0y4ym2yb',
       'cx:13107309109141761847803:1e1rswsawyyc3',
       'cx:13107395951811145781879:31h108vvvw6te',
       'cx:1311701842831565911801:20af369r0nju6',
       ...
       'cx:xgx9bvnqjnwn3na33zslm41j6:1141wmv8rxo4m',
       'cx:xz8qx9tccgls29jx1ggejvc2o:3dcgsybzandnb',
       'cx:xzx3d9an4u6r614zazbm41gx:3d1u2by0zprqf',
       'cx:y3ojtj1dah373vh26yiostnfa:3bnuogklc05m0',
       'cx:ym4dpjqbcqqp138to9m6mm0m7:2mgigrnofe6bf',
       'cx:ymgd4qz84t6z31b22zecmrpz3:2bclyyq01sfwd',
       'cx:ywxiqgtmxyfc24eqhyzpz7jer:28kehwib7kyi8',
       'cx:z5nmgvym79d91yxajr8rncjp3:dd23bgkvv19x',
       'cx:zdxhidle29xquzztafvsik92:2w17zz40qj619',
   

In [33]:
print(clean.index)

Index(['cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7',
       'cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694',
       'cx:13077170178592105431908:2so1nc52xur4d',
       'cx:13082126012361420762846:3nhzg71lk2zqc',
       'cx:13082926635761580649288:30q2cgmwa3mzi',
       'cx:1308583952725345187693:udud1r6r2t9x',
       'cx:1309558690741378897676:2952b0y4ym2yb',
       'cx:13107309109141761847803:1e1rswsawyyc3',
       'cx:13107395951811145781879:31h108vvvw6te',
       'cx:1311701842831565911801:20af369r0nju6',
       ...
       'cx:xgx9bvnqjnwn3na33zslm41j6:1141wmv8rxo4m',
       'cx:xz8qx9tccgls29jx1ggejvc2o:3dcgsybzandnb',
       'cx:xzx3d9an4u6r614zazbm41gx:3d1u2by0zprqf',
       'cx:y3ojtj1dah373vh26yiostnfa:3bnuogklc05m0',
       'cx:ym4dpjqbcqqp138to9m6mm0m7:2mgigrnofe6bf',
       'cx:ymgd4qz84t6z31b22zecmrpz3:2bclyyq01sfwd',
       'cx:ywxiqgtmxyfc24eqhyzpz7jer:28kehwib7kyi8',
       'cx:z5nmgvym79d91yxajr8rncjp3:dd23bgkvv19x',
       'cx:zdxhidle29xquzztafvsik92:2w17zz40qj619',
   

In [34]:
mask = clean.activeTime.isnull()
clean.activeTime[~mask] = np.where(clean.activeTime < 0.5,  -1.0, 1.0)

In [35]:
clean.head()

activeTime  \
documentId                                  0006b2caef9ae801cfa0a48ec737544241ec4dca   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  00098cc438af89c1ba8fb6a37035af2e2f606ce3   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  000fd9e1ee3153e955d5e64b35691d799189aa2d   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                        -1.0   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0020dd5ded93f94d4d078151a7733bb8410838fd   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0022652ffa4a9f8a041b5b4fb7591aacda920d31   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:13082126012361420762846:3nhzg71lk2zqc                                         NaN   
cx:13082926635761580649288:30q2cgmwa3mzi                                         NaN   

                                                                                      \
documentId                                  0023cf8c8637599ee493463a429f4af62817cf3a   
userId                                                                                 
cx:10k2wzm1b3jsk2y5ym1utnjo97:2kefzqaxe9jx7                                      NaN   
cx:11asuyo07mbi13b849lp87hlje:1i9z1hu1xx694                                      NaN   
cx:13077170178592105431908:2so1nc52xur4d                                         NaN   
cx:130821260123614207

In [36]:
newCleaned = clean_dataset_0_1_1(clean)

/home/vanja/anaconda3/envs/Recommender/lib/python3.8/site-packages/numpy/core/_methods.py:160: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)


In [42]:
finalData = clean_activeTime_zeros(newCleaned)

In [44]:
print(finalData[:30])

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. -1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]


In [38]:
#df.fillna(0)

In [39]:
reducedSet = clean_activeTime_zeros(newSet)

In [40]:
print(reducedSet[:20])

[[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.  15. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   0. 122.   0.]]


In [41]:
print(reducedSet.shape)

(994, 14351)
